<?php

namespace ContainerLRlUkkz;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TXM5QlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tX_m5Ql' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tX_m5Ql'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'homework' => ['privates', '.errored..service_locator.tX_m5Ql.App\\Entity\\Homework', NULL, 'Cannot autowire service ".service_locator.tX_m5Ql": it needs an instance of "App\\Entity\\Homework" but this type has been excluded in "config/services.yaml".'],
        ], [
            'homework' => 'App\\Entity\\Homework',
        ]);
    }
}
