<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\LoginController::login'], [], [['text', '/login']], [], [], []],
    'authenticated_page' => [[], ['_controller' => 'App\\Controller\\LoginController::authenticatedPage'], [], [['text', '/authenticated-page']], [], [], []],
    'app_homepage' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/']], [], [], []],
    'add_homework' => [[], ['_controller' => 'App\\Controller\\HomeworkController::addHomework'], [], [['text', '/add-homework']], [], [], []],
    'login_check' => [[], ['_controller' => 'App\\Controller\\LoginController::login'], [], [['text', '/login']], [], [], []],
    'edit_homework' => [['id'], ['_controller' => 'App\\Controller\\EdithomeworkController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/edit_homework']], [], [], []],
    'popup_content' => [[], ['_controller' => 'App\\Controller\\PopupController::popupContent'], [], [['text', '/popup-content']], [], [], []],
    'manage_students' => [[], ['_controller' => 'App\\Controller\\AdminController::studentContent'], [], [['text', '/student']], [], [], []],
    'manage_teachers' => [[], ['_controller' => 'App\\Controller\\AdminController::teachersContent'], [], [['text', '/profs']], [], [], []],
    'manage_classes' => [[], ['_controller' => 'App\\Controller\\AdminController::classesContent'], [], [['text', '/classes']], [], [], []],
    'get_teacher' => [['id'], ['_controller' => 'App\\Controller\\AdminController::getTeacher'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/get-teacher']], [], [], []],
    'edit_teacher' => [['id'], ['_controller' => 'App\\Controller\\AdminController::editTeacher'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/edit-teacher']], [], [], []],
    'delete_user' => [['id'], ['_controller' => 'App\\Controller\\AdminController::deleteUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/delete-user']], [], [], []],
    'delete_classe' => [['id'], ['_controller' => 'App\\Controller\\AdminController::deleteClasse'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/delete-classe']], [], [], []],
    'update_homework' => [['id'], ['_controller' => 'App\\Controller\\EdithomeworkController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/homework/update']], [], [], []],
    'delete_homework' => [['id'], ['_controller' => 'App\\Controller\\EdithomeworkController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/homework/delete']], [], [], []],
    'admin_dashboard' => [[], ['_controller' => 'App\\Controller\\AdminController::dashboard'], [], [['text', '/admin/dashboard']], [], [], []],
    'add_user' => [[], ['_controller' => 'App\\Controller\\AdminController::addUser'], [], [['text', '/add-user']], [], [], []],
    'add_class' => [[], ['_controller' => 'App\\Controller\\AdminController::addClasse'], [], [['text', '/add-classe']], [], [], []],
    'add_student' => [[], ['_controller' => 'App\\Controller\\AdminController::addStudent'], [], [['text', '/add-student']], [], [], []],
    'add_teachers' => [[], ['_controller' => 'App\\Controller\\AdminController::addTeacher'], [], [['text', '/add-teacher']], [], [], []],
];
